/* nestly_v723 — CI-100 check 92 (UI/RPC contract validation), platform-console half.
 *
 * docs/design/ci/CI-READER-CONTRACTS.json (generated by scripts/quality/ci-reader-contracts.mjs)
 * covers the 25 public.get_ci_* readers plus get_customer_intelligence_v83 and
 * app.v176_evidence_pack. tests/business-ui/v723-ci-reader-contracts.test.mjs proves app/app.js's
 * Customer Intelligence panels against it. This file is the platform-console.js half, following
 * the harness tests/platform-console/v667-consultative-payload.test.mjs established: execute the
 * real renderer via vm against a fixture, then grep the renderer's own source for the payload
 * paths it reads.
 *
 * WHY THIS FILE LOOKS DIFFERENT FROM ITS business-ui SIBLING. Grepped, not assumed:
 * app/platform-console.js's consultative brief (consultativeIntelligenceHtml, the renderer
 * v667-consultative-payload.test.mjs already covers) reads `report.kpis`, `report.cohorts` and
 * `affinity.pairs` — all from platform_get_assigned_firm_report_v94 / platform_get_catalogue_
 * affinity_v94, a completely different RPC pair with its own contract, not any of the 27 readers
 * CI-READER-CONTRACTS.json declares. The one dead reference to `report.customer_intelligence`
 * (a superseded v94 key nestly_v667 already proved is never populated) is not one of these 27
 * readers either. And the AI-report drawer (loadAiReports / renderAiReportRow) reads
 * `report.narrative_md`/`report.status`/`report.id` off `ai_firm_reports_v176` rows — the CLAIMED
 * table row, not a live call to app.v176_evidence_pack, which only ever runs inside the
 * ai-firm-reports edge function and is consumed by the model, never fetched into the browser (see
 * app.v176_evidence_pack's own header comment and supabase/functions/ai-firm-reports/index.ts).
 * So there is currently no platform-console.js renderer to execute against a get_ci_ / v83 / v176
 * fixture — but check 92 still demands proof, not an assumption, that this stays true, and a
 * FORWARD guard so the day a platform screen starts reading one of these 27 readers directly,
 * this file starts enforcing the same declared-access contract app/app.js already is held to.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const consoleJs = readFileSync(join(root, 'app', 'platform-console.js'), 'utf8');

const contractsGen = await import(join(root, 'scripts', 'quality', 'ci-reader-contracts.mjs'));
const { CONTRACTS, JSON_PATH } = contractsGen;

/* Strip comments before scanning for code, same discipline v667-consultative-payload.test.mjs
   uses: a comment can name a superseded/dead RPC to explain history (this very file does, in its
   own header above) without that mention counting as a live call site. */
const code = consoleJs.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:])\/\/[^\n]*/g, '$1 ');

/* Every reader name CI-READER-CONTRACTS.json declares, in the two forms a live call site could
   spell it: `rpc(sb,'NAME'` / `.rpc('NAME'` for the public.* ones (Supabase RPC calls are never
   schema-qualified in the JS call), and the bare qualified name for app.v176_evidence_pack (which
   has no browser call path at all — see the file header — so its search string is the qualified
   name itself, unlikely to appear anywhere outside a comment). */
function callSitePatterns(readerFullName) {
  if (readerFullName.startsWith('public.')) {
    const bare = readerFullName.slice('public.'.length);
    return [new RegExp(`\\.rpc\\(\\s*['"]${bare}['"]`, 'g')];
  }
  return [new RegExp(readerFullName.replace('.', '\\.'), 'g')];
}

test('v723 CI-READER-CONTRACTS.json loads and covers the expected 27 readers (platform side sees the same contract)', () => {
  const onDisk = JSON.parse(readFileSync(JSON_PATH, 'utf8'));
  assert.strictEqual(Object.keys(onDisk.readers).length, 27);
  assert.deepStrictEqual(Object.keys(onDisk.readers).sort(), Object.keys(CONTRACTS).sort());
});

test('v723 platform-console.js currently calls none of the 25 get_ci_* readers directly', () => {
  const hits = [];
  for (const name of Object.keys(CONTRACTS)) {
    if (!name.startsWith('public.get_ci_')) continue;
    for (const pattern of callSitePatterns(name)) {
      if (pattern.test(code)) hits.push(name);
    }
  }
  assert.deepStrictEqual(hits, [],
    'app/platform-console.js now calls a get_ci_* reader this test did not expect — add contract ' +
    'enforcement for its renderer here (mirror tests/business-ui/v723-ci-reader-contracts.test.mjs\'s ' +
    'buildFixture/assertAccessesDeclared pattern) rather than leaving this assertion to rot');
});

test('v723 platform-console.js does not call get_customer_intelligence_v83 directly', () => {
  const pattern = /\.rpc\(\s*['"]get_customer_intelligence_v83['"]/g;
  assert.strictEqual(pattern.test(code), false,
    'app/platform-console.js now calls get_customer_intelligence_v83 — add contract enforcement ' +
    'for its renderer here');
});

test('v723 app.v176_evidence_pack has no browser call site in platform-console.js (model-only, per its own header)', () => {
  const pattern = /v176_evidence_pack/g;
  assert.strictEqual(pattern.test(code), false,
    'app/platform-console.js now references v176_evidence_pack outside a comment — it was model-' +
    'only (consumed inside supabase/functions/ai-firm-reports, never fetched into the browser); if ' +
    'that has changed, add contract enforcement for the new renderer here');
});

/* The one dead key nestly_v667 already found and left as a documented landmine: prove it stays
   dead rather than re-reading it under a false belief it maps to one of the 27 contract readers.
   (v667-consultative-payload.test.mjs already asserts the renderer no longer READS this key as a
   value; this assertion is narrower and specific to check 92 — that `customer_intelligence` is
   not, and must not become, a stand-in name for one of the get_ci_ / v83 payloads.) */
test('v723 consultativeIntelligenceHtml\'s dead `report.customer_intelligence` key is not one of the 27 contract readers', () => {
  assert.ok(
    !Object.keys(CONTRACTS).some((name) => name.includes('customer_intelligence') && name !== 'public.get_customer_intelligence_v83'),
    'a reader literally named customer_intelligence would make the v667 dead-key landmine and this ' +
    'contract collide — confirms the two vocabularies stay distinct');
});
