import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {currentProductionVisualFixture} from '../browser/generate-v104-promotions-visual.mjs';

const fixture=await readFile(
  new URL('../browser/v104-promotions-visual.html',import.meta.url),
  'utf8'
);
const metrics=JSON.parse(await readFile(
  new URL('../../docs/qa/evidence/v104-promotions-production-render-metrics.json',import.meta.url),
  'utf8'
));

test('visual fixture is generated byte-for-byte from current production render functions and CSS',async()=>{
  assert.equal(fixture,await currentProductionVisualFixture());
  assert.match(fixture,/meta name="v104-production-source-sha256" content="[a-f0-9]{64}"/);
  assert.match(fixture,/function customerPromotionCardV104/);
  assert.match(fixture,/function openCustomerPromotionDetailsV104/);
  /* v192 dropped the 360px floor — a two-offer list ran past three phone screens. The point of
     this assertion is that the fixture carries PRODUCTION css, not a hand-written copy, so it
     tracks the current rule rather than the old number. */
  assert.match(fixture,/\.customer-promotion-card\{position:relative;overflow:hidden;border-radius:18px/);
  assert.doesNotMatch(fixture,/\.customer-promotion-card\{display:flex;min-height:360px/,
    'independent legacy fixture CSS must never masquerade as production evidence');
});

test('actual-render fixture uses realistic spa data and exactly two primary offers',()=>{
  assert.match(fixture,/Glow Atelier/);
  assert.match(fixture,/30% off Spa Ritual 60/);
  assert.match(fixture,/2026-08-30T23:59:59\+08:00/);
  assert.equal(
    (fixture.match(/"id":"[12]{8}-/g)||[]).length,
    2
  );
  assert.match(fixture,/Book now/);
  assert.match(fixture,/View details/);
  assert.match(fixture,/Valid \$\{starts\} – \$\{ends\}/);
});

test('actual-render fixture keeps identity compact, wraps long tokens, and exposes a real modal',()=>{
  assert.match(fixture,/customer-programme-compact-head/);
  /* v326 (owner: "in phone view, please put side by side to swipe, don't arrange above &
     bottom"): the combined .customer-promotions-grid,.promotion-editor-grid single-column rule
     split in two — the customer offers row now scrolls horizontally at this breakpoint instead,
     while the business-side promotion editor grid keeps its original single-column stack. */
  assert.match(
    fixture,
    /@media\(max-width:768px\)\{[\s\S]*\.promotion-editor-grid\{grid-template-columns:1fr\}/
  );
  assert.match(
    fixture,
    /\.customer-promotions-grid\{display:flex;grid-template-columns:none;overflow-x:auto;scroll-snap-type:x mandatory/
  );
  assert.match(fixture,/meta name="viewport" content="width=device-width,initial-scale=1"/);
  assert.match(fixture,/overflow-wrap:anywhere;word-break:break-word/);
  assert.match(
    fixture,
    /\.customer-promotion-card-copy h3\{[^}]*color:#fff\}/,
    'marketing headlines must keep readable white contrast over offer media'
  );
  assert.match(fixture,/NESTLY-NDP-2026-/);
  assert.doesNotMatch(fixture,/<text[^>]*>NATIONAL DAY SPA<\/text>/);
  assert.match(fixture,/role="dialog" aria-modal="true"/);
  assert.match(fixture,/CUI\.activateDialog/);
  assert.match(fixture,/\.customer-promotion-card details\{min-width:0\}/);
  assert.match(fixture,/\.customer-promotion-card details\[open\]\{flex:1 1 100%;width:100%\}/);
  assert.match(fixture,/window\.v104OpenTerms=/);
  assert.match(fixture,/availableContentWidth:/);
  assert.match(fixture,/textOverflow:/);
  assert.match(fixture,/#customerPromotionDetailsModal h2,#customerPromotionDetailsModal p,#customerPromotionDetailsModal dd/);
  assert.match(fixture,/id='v104AcceptanceReport'/);
  assert.match(fixture,/evidenceParams\.get\('openModal'\)==='1'/);
});

test('captured Chrome evidence is current and meets responsive acceptance thresholds',()=>{
  const sourceHash=fixture.match(/meta name="v104-production-source-sha256" content="([a-f0-9]{64})"/)?.[1];
  assert.ok(sourceHash);
  const expectedWidths={desktop1440:1440,mobile390:390,mobile412:412};
  for(const [name,width] of Object.entries(expectedWidths)){
    const capture=metrics[name];
    assert.equal(capture.sourceHash,sourceHash,`${name} must come from current production source`);
    assert.deepEqual(capture.viewport,{clientWidth:width,scrollWidth:width});
    assert.equal(capture.cards.length,2);
    assert.ok(capture.cards.every(card=>card.ctaHeight>=44));
    assert.ok(capture.cards.every(card=>/^Valid .+ – .+$/.test(card.validity)));
  }

  /* v326 (owner: "in phone view, please put side by side to swipe, don't arrange above &
     bottom"): offer cards used to stack vertically on phone widths; they now sit in one
     horizontally-scrolling row, so card two starts beside card one (same top, to its right)
     rather than below it. */
  for(const capture of [metrics.mobile390,metrics.mobile412]){
    assert.ok(Math.abs(capture.cards[1].rect.top-capture.cards[0].rect.top)<2,
      'cards sit in the same row on phone widths');
    assert.ok(capture.cards[1].rect.left>=capture.cards[0].rect.right,
      'card two starts beside card one, not overlapping it');
  }

  const firstTerms=metrics.mobile390.cards[0].details;
  assert.equal(firstTerms.open,true);
  assert.equal(firstTerms.width,firstTerms.availableContentWidth);
  assert.equal(firstTerms.scrollWidth,firstTerms.clientWidth);
  assert.equal(firstTerms.scrollHeight,firstTerms.clientHeight);

  const longTerms=metrics.mobile412.cards[1].details;
  assert.equal(longTerms.open,true);
  assert.equal(longTerms.width,longTerms.availableContentWidth);
  assert.equal(longTerms.scrollWidth,longTerms.clientWidth);
  assert.equal(longTerms.scrollHeight,longTerms.clientHeight);
  assert.equal(metrics.mobile412.longTokenVisible,true);

  assert.deepEqual(
    {
      role:metrics.desktop1440.modal.role,
      ariaModal:metrics.desktop1440.modal.ariaModal,
      labelledBy:metrics.desktop1440.modal.labelledBy,
      activeElement:metrics.desktop1440.modal.activeElement
    },
    {
      role:'dialog',
      ariaModal:'true',
      labelledBy:'customerPromotionDetailsTitle',
      activeElement:'customerPromotionDetailsClose'
    }
  );
  assert.ok(metrics.desktop1440.modal.textOverflow.length>=4);
  assert.ok(metrics.desktop1440.modal.textOverflow.every(node=>
    node.scrollWidth<=node.clientWidth&&node.scrollHeight<=node.clientHeight
  ));
});
