/* nestly_v723 — CI-100 check 92 (UI/RPC contract validation), business-UI half.
 *
 * docs/design/ci/CI-READER-CONTRACTS.json (generated by scripts/quality/ci-reader-contracts.mjs)
 * is the single machine-readable contract for the 25 public.get_ci_* readers plus
 * get_customer_intelligence_v83 and app.v176_evidence_pack. db/tests/executed/
 * v723_corpus_reader_contracts.sql proves the SQL side (every declared top-level key exists with
 * the declared jsonb_typeof() on a real, minimally-seeded call). This file proves the browser
 * side of the same check, in the tradition tests/platform-console/v667-consultative-payload.
 * test.mjs established: EXECUTE the real renderer (never a hand-copied re-implementation) via
 * vm, against a fixture built from nothing but the contract's declared keys, and separately grep
 * the renderer's own source for every `payload.foo.bar` chain it reads, requiring each to be a
 * path the contract actually declares. A source-regex test that only checks "the string exists
 * somewhere in the file" would not have caught nestly_v667's defect (superseded key names that
 * happened to still appear in a comment); this extracts and executes real code instead.
 *
 * Renderers covered: funnelConversionPanelHtmlV679, demographicsPanelHtmlV679,
 * behaviourPanelHtmlV679, opportunitiesPanelHtmlV685, ciOpportunityCardHtmlV685 (all five are
 * pure top-level functions of their payload — same posture as recoveryReportHtmlV550, per the
 * nestly_v679 header comment above them in app/app.js) and categoryMixMarkupV650 (NOT pure — it
 * reads customerIntelligencePage's own closure state, so it is exercised through a thin,
 * clearly-marked rewrite that substitutes a `bundle` parameter for the closure reads; every
 * substitution is listed at CATEGORY_MIX_REWRITES below so a reviewer can see exactly what was
 * changed and why).
 *
 * GAP CLOSURE (this pass, check 92 §a): four more consuming renderers, same posture as
 * categoryMixMarkupV650 above — each reads its own `lastXBundle`/`lastXError` page-closure
 * state rather than taking a payload parameter, so each is exercised the same way: extract the
 * real source, supply the closure variables (and the small in-page helpers the block calls,
 * e.g. ciQuietErrorV650/ciMeasuredSinceV650) as vm sandbox globals, run it unmodified.
 *   - acquisitionMarkupV650   (public.get_ci_acquisition_v1)
 *   - funnelMarkupV650        (public.get_ci_funnel_v1)
 *   - contactabilityMarkupV650(public.get_ci_contactability_v1)
 *   - ciCategoryCustomersRowsMarkupV650 (public.get_ci_category_customers_v1) — reads a
 *     `categoryCustomersCacheV650.get(nodeKey)` cache entry rather than a bundle directly;
 *     exercised with a real Map holding `{data: <fixture>}`, same idea, one more layer of
 *     indirection.
 * ciOpportunityCardHtmlV685's execution above already calls every nestly_v716 impact-
 * translation helper (ciOpportunityMaterialityChipHtmlV716/ciOpportunityMarginHtmlV716/
 * ciOpportunityCapacityHtmlV716/ciOpportunityRetentionRiskHtmlV716/
 * ciOpportunityConcentrationHtmlV716/ciOpportunityAlternativesListHtmlV716) as plain calls in
 * its own body — no separate wiring needed; a dedicated assertion below checks their markup
 * actually appears in the rendered HTML so this stays proven, not assumed. There are no
 * v719-named helpers anywhere in app/app.js (grepped at the time of this pass) — nothing to add.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import vm from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const appJs = readFileSync(join(root, 'app', 'app.js'), 'utf8');

const contractsGen = await import(join(root, 'scripts', 'quality', 'ci-reader-contracts.mjs'));
const { CONTRACTS, buildDoc, extractEmbedded, JSON_PATH } = contractsGen;

/* ------------------------------------------------------------ generator/artifact consistency */

test('v723 CI-READER-CONTRACTS.json matches the generator source', () => {
  const onDisk = JSON.parse(readFileSync(JSON_PATH, 'utf8'));
  assert.deepStrictEqual(onDisk, buildDoc(),
    'docs/design/ci/CI-READER-CONTRACTS.json is stale — rerun `node scripts/quality/ci-reader-contracts.mjs`');
});

test('v723 the embedded SQL literal matches the generator source (same one, not a hand copy)', () => {
  const embedded = extractEmbedded();
  assert.ok(embedded, 'db/tests/executed/v723_corpus_reader_contracts.sql must carry the ' +
    'CI-READER-CONTRACTS-EMBED-BEGIN/END markers with a parseable literal inside');
  assert.deepStrictEqual(embedded, buildDoc(),
    'the embedded literal in v723_corpus_reader_contracts.sql is stale relative to the generator ' +
    '— rerun `node scripts/quality/ci-reader-contracts.mjs` (never hand-edit the embedded block)');
});

test('v723 exactly 27 readers are under contract (25 get_ci_* + v83 + v176 evidence pack)', () => {
  const names = Object.keys(CONTRACTS);
  assert.strictEqual(names.length, 27);
  const ciReaders = names.filter((n) => /get_ci_/.test(n));
  assert.strictEqual(ciReaders.length, 25);
  assert.ok(names.includes('public.get_customer_intelligence_v83'));
  assert.ok(names.includes('app.v176_evidence_pack'));
});

/* --------------------------------------------------------------------- fixture construction */

/* Builds the minimal object a reader's `nested` (or `required`, when nested is empty) contract
   describes — ONLY the keys the contract lists as required (never the ones marked __optional),
   each set to a representative value of its declared type. A "TYPE|null" union always picks the
   non-null branch: the point of this fixture is the renderer's real, populated-data code path,
   not its guard clauses (those are covered by the empty/error states the page's own
   ciEmptyPanelV679 / ciQuietErrorV650 wiring already handles, outside these pure renderers). */
function leafValue(declaredType) {
  const first = declaredType.split('|').find((t) => t !== 'null') || declaredType.split('|')[0];
  switch (first) {
    case 'string': return 'x';
    case 'number': return 1;
    case 'boolean': return true;
    case 'object': return {};
    case 'array': return [];
    default: return null;
  }
}

function buildFixture(nested, requiredTopLevel) {
  const optional = new Set(nested.__optional || []);
  const entries = Object.entries(nested).filter(([k]) => k !== '__optional' && !optional.has(k));
  const root = {};
  // Ensure every top-level required key exists even if `nested` never drills into it.
  for (const [key, type] of Object.entries(requiredTopLevel || {})) {
    if (!(key in root)) root[key] = leafValue(type);
  }
  // Sort shallowest-first so parent containers are established before children are written.
  entries.sort((a, b) => a[0].split('.').length - b[0].split('.').length);
  for (const [path, type] of entries) {
    const segments = path.split('.');
    let cursor = root;
    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i];
      const isLast = i === segments.length - 1;
      if (seg === '*') {
        if (!Array.isArray(cursor)) continue; // contract bug guard; should not happen
        if (cursor.length === 0) cursor.push({});
        cursor = cursor[0];
        continue;
      }
      if (isLast) {
        cursor[seg] = leafValue(type);
      } else {
        const nextIsArrayIndex = segments[i + 1] === '*';
        if (!(seg in cursor) || typeof cursor[seg] !== 'object' || cursor[seg] === null) {
          cursor[seg] = nextIsArrayIndex ? [] : {};
        }
        cursor = cursor[seg];
      }
    }
  }
  return root;
}

/* --------------------------------------------------------------- payload-access extraction */

/* Conservative extractor: walks the renderer source for `root.a.b` / `root?.a?.b` chains where
   `root` is a tracked variable (a function parameter, or a local alias discovered from
   `const x=root.a` / `root.map(x=>...)` / destructuring `const {a,b}=root`), normalizes optional
   chaining and array iteration to the same dotted-path-with-`.*` notation the contract uses, and
   drops any chain whose final segment is a known Array/Object/String prototype method rather than
   a real payload key. Conservative means it can MISS an access (e.g. one reached through a alias
   this heuristic does not model) but every chain it DOES report is a real property read in the
   source — false negatives are possible, false positives are not silently accepted (the assertion
   below fails loudly if a reported path isn't declared, so a miss just means "not yet guarded",
   never a false alarm blocking unrelated work). */
const JS_METHOD_NAMES = new Set([
  'map', 'filter', 'find', 'findIndex', 'some', 'every', 'reduce', 'forEach', 'join', 'slice',
  'length', 'toFixed', 'toString', 'includes', 'indexOf', 'push', 'pop', 'concat', 'sort',
  'replace', 'replaceAll', 'trim', 'split', 'keys', 'values', 'entries', 'has', 'get', 'set',
  'isArray', 'flat', 'flatMap', 'charAt', 'toUpperCase', 'toLowerCase',
]);

/* Joins a base dotted-path (possibly '' for "the root object itself") with further segments,
   without leaving a stray leading dot when base is ''. */
function joinPath(base, segs) {
  return [base, ...segs].filter((s) => s !== '').join('.');
}

/* `rootVarMap` is { varName: basePath }, e.g. {payload:'', item:'ranked.*'} — payload IS the
   contract's root object (basePath ''), item is one element of the ranked array. */
function extractAccesses(source, rootVarMap) {
  const aliases = new Map(Object.entries(rootVarMap));
  // const X = ROOT (bare copy, no property access — e.g. `const p=payload;`)
  for (const m of source.matchAll(/const\s+([a-zA-Z_$][\w$]*)\s*=\s*([a-zA-Z_$][\w$]*)\s*[;,)]/g)) {
    const [, alias, base] = m;
    if (!aliases.has(base) || aliases.has(alias)) continue;
    aliases.set(alias, aliases.get(base));
  }
  // const X = ROOT?.a?.b (alias assignment through a property chain, optionally with ||{} / ||[])
  for (const m of source.matchAll(/const\s+([a-zA-Z_$][\w$]*)\s*=\s*([a-zA-Z_$][\w$]*)((?:\??\.[a-zA-Z_$][\w$]*)+)/g)) {
    const [, alias, base, chain] = m;
    if (!aliases.has(base)) continue;
    const segs = chain.split(/\??\./).filter(Boolean);
    aliases.set(alias, joinPath(aliases.get(base), segs));
  }
  // ROOT.map(alias=>...) / ROOT.map((alias)=>...) / ROOT.a.b.map(alias=>...)
  for (const m of source.matchAll(/([a-zA-Z_$][\w$.?]*)\.map\(\(?([a-zA-Z_$][\w$]*)\)?\s*=>/g)) {
    const [, chainExpr, alias] = m;
    const parts = chainExpr.split(/\??\./).filter(Boolean);
    const rootTok = parts.shift();
    if (!aliases.has(rootTok)) continue;
    aliases.set(alias, joinPath(joinPath(aliases.get(rootTok), parts), ['*']));
  }
  // destructuring: const {a,b:renamed}=ROOT (only bare/renamed identifiers, no defaults/nesting)
  for (const m of source.matchAll(/const\s*\{([^}]+)\}\s*=\s*([a-zA-Z_$][\w$]*)\s*[;,)]/g)) {
    const [, fields, base] = m;
    if (!aliases.has(base)) continue;
    for (const rawField of fields.split(',')) {
      const f = rawField.trim();
      if (!f || f.includes('...')) continue;
      const [srcName, destName] = f.split(':').map((s) => s.trim());
      if (!srcName) continue;
      aliases.set(destName || srcName, joinPath(aliases.get(base), [srcName]));
    }
  }

  const found = new Set();
  const rootAlt = [...aliases.keys()].sort((a, b) => b.length - a.length)
    .map((v) => v.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  if (!rootAlt) return found;
  const chainRe = new RegExp(`\\b(${rootAlt})((?:\\??\\.[a-zA-Z_$][\\w$]*)+)`, 'g');
  for (const m of source.matchAll(chainRe)) {
    const [, base, chain] = m;
    const baseDotted = aliases.get(base);
    const segs = chain.split(/\??\./).filter(Boolean);
    while (segs.length && JS_METHOD_NAMES.has(segs[segs.length - 1])) segs.pop();
    if (!segs.length) continue;
    const full = joinPath(baseDotted, segs);
    if (full) found.add(full);
  }
  return found;
}

/* A path found in source (e.g. "ranked.0.impact.cents" never occurs — array indices in source
   are always the alias-derived ".*") is checked directly against the contract's `nested` map,
   whose keys are already in ".*"-normalized dotted-path form. */
function assertAccessesDeclared(readerName, source, rootVars, extraDeclaredPrefixes = []) {
  const contract = CONTRACTS[readerName];
  assert.ok(contract, `${readerName} must be declared in CONTRACTS`);
  const declared = new Set(Object.keys(contract.nested || {}).filter((k) => k !== '__optional'));
  // A bare intermediate read (e.g. `p.stage_1_to_2` passed whole into ciRateBlockV679, before
  // ciRateBlockV679 pulls .numerator/.denominator/.pct off it) is covered as long as the
  // contract declares at least one deeper path under it — the leaf declarations are what prove
  // the object's real shape; the intermediate read itself invents no new key.
  const isDeclared = (path) => declared.has(path) || [...declared].some((d) => d.startsWith(`${path}.`));
  const accesses = extractAccesses(source, rootVars);
  const undeclared = [...accesses].filter((path) =>
    !isDeclared(path) && !extraDeclaredPrefixes.some((prefix) => path === prefix || path.startsWith(`${prefix}.`)));
  assert.deepStrictEqual(undeclared, [],
    `${readerName}: renderer reads path(s) not declared in CI-READER-CONTRACTS.json nested map: ${undeclared.join(', ')}`);
}

/* --------------------------------------------------------------------------- vm plumbing */

function extractBlock(startMarker, endMarker) {
  const start = appJs.indexOf(startMarker);
  const end = appJs.indexOf(endMarker, start);
  assert.ok(start > -1 && end > start, `could not locate block ${startMarker} .. ${endMarker}`);
  return appJs.slice(start, end);
}

const OPPORTUNITIES_BLOCK = extractBlock(
  'function ciOpportunityConfidenceV685(confidence){',
  'async function serviceMappingBoardPage(){',
);

/* nestly_v723 gap-closure (a): the "revenue truth" v650 quartet — acquisitionMarkupV650,
   ciFunnelStepsMarkupV650+funnelMarkupV650, ciContactabilityGroupMarkupV650+
   contactabilityMarkupV650 — plus their shared helpers (CI_ACQUISITION_VIA_LABELS_V650,
   ciViaLabelV650, ciQuietErrorV650, ciMeasuredSinceV650). All read page-closure `let
   lastXBundle/lastXError` variables rather than taking a payload parameter (see the block's own
   nestly_v650 comment in app/app.js just above CI_ACQUISITION_VIA_LABELS_V650), so the vm
   sandbox supplies those as plain globals instead of rewriting the functions into pure ones. */
const V650_ACQUISITION_FUNNEL_CONTACTABILITY_BLOCK = extractBlock(
  'const CI_ACQUISITION_VIA_LABELS_V650={',
  'const CI_CATEGORY_MIX_READY_THRESHOLD_BPS_V650=9000;',
);

function runBlock(block, exportName, args) {
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
  const money = (c) => 'SGD ' + ((Number(c) || 0) / 100).toFixed(2);
  const walletDate = (v) => String(v ?? '');
  const sandbox = { esc, money, walletDate, console };
  const context = vm.createContext(sandbox);
  context.__exports = {};
  vm.runInContext(`${block}\n__exports.fn = ${exportName};`, context);
  return context.__exports.fn(...args);
}

/* Same idea as runBlock, but for the v650 quartet: it also seeds the page-closure `lastXBundle`/
   `lastXError` globals the block reads instead of passing a fixture as a function argument. */
function runV650Block(exportName, closureVars) {
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
  const walletDate = (v) => String(v ?? '');
  const sandbox = { esc, walletDate, console, ...closureVars };
  const context = vm.createContext(sandbox);
  context.__exports = {};
  vm.runInContext(`${V650_ACQUISITION_FUNNEL_CONTACTABILITY_BLOCK}\n__exports.fn = ${exportName};`, context);
  return context.__exports.fn();
}

/* ------------------------------------------------------------------------------ the tests */

test('v723 funnelConversionPanelHtmlV679 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_funnel_conversion_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const html = runBlock(OPPORTUNITIES_BLOCK, 'funnelConversionPanelHtmlV679', [fixture]);
  assert.ok(typeof html === 'string' && html.length > 0);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

test('v723 demographicsPanelHtmlV679 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_demographics_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const html = runBlock(OPPORTUNITIES_BLOCK, 'demographicsPanelHtmlV679', [fixture]);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

test('v723 behaviourPanelHtmlV679 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_daypart_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const html = runBlock(OPPORTUNITIES_BLOCK, 'behaviourPanelHtmlV679', [fixture]);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

test('v723 opportunitiesPanelHtmlV685 (and ciOpportunityCardHtmlV685 via it) renders cleanly', () => {
  const contract = CONTRACTS['public.get_ci_opportunities_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const html = runBlock(OPPORTUNITIES_BLOCK, 'opportunitiesPanelHtmlV685', [fixture]);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

test('v723 ciOpportunityCardHtmlV685 renders a single ranked item cleanly, called directly', () => {
  const contract = CONTRACTS['public.get_ci_opportunities_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const item = fixture.ranked[0];
  const html = runBlock(OPPORTUNITIES_BLOCK, 'ciOpportunityCardHtmlV685', [item, fixture.scope.currency]);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

test('v723 ciOpportunityCardHtmlV685 actually invokes every nestly_v716 impact helper (not vestigial)', () => {
  // Same fixture/call as the test above — this just proves each v716 helper's own markup
  // reached the output, not merely that the card rendered without "undefined"/"NaN".
  const contract = CONTRACTS['public.get_ci_opportunities_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const item = fixture.ranked[0];
  item.materiality_class = 'material';
  item.margin_guard = { status: 'ok', margin_cents: 1000, reason: '' };
  item.impact.capacity = { status: 'ok', pct: 50, booked_minutes: 30, available_minutes: 60, reason: '' };
  item.impact.retention_risk = { status: 'ok', at_risk_n: 2, reason: '' };
  item.concentration = { skew_note: 'x' };
  item.alternatives = [{ primary: true, what: 'x', kind: 'incentive' }];
  const html = runBlock(OPPORTUNITIES_BLOCK, 'ciOpportunityCardHtmlV685', [item, fixture.scope.currency]);
  assert.ok(html.includes('ci-opportunity-materiality-chip'), 'ciOpportunityMaterialityChipHtmlV716 did not render');
  assert.ok(html.includes('Margin ok'), 'ciOpportunityMarginHtmlV716 did not render');
  assert.ok(html.includes('min booked'), 'ciOpportunityCapacityHtmlV716 did not render');
  assert.ok(html.includes('at risk'), 'ciOpportunityRetentionRiskHtmlV716 did not render');
  assert.ok(html.includes('ci-opportunity-concentration'), 'ciOpportunityConcentrationHtmlV716 did not render');
  assert.ok(html.includes('ci-opportunity-alternatives'), 'ciOpportunityAlternativesListHtmlV716 did not render');
});

test('v723 acquisitionMarkupV650 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_acquisition_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const html = runV650Block('acquisitionMarkupV650', {
    lastAcquisitionError: '', lastAcquisitionBundle: fixture,
  });
  assert.ok(typeof html === 'string' && html.length > 0);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

test('v723 funnelMarkupV650 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_funnel_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  // `funnel.join`/`funnel.booking` are __optional (nestly_v698's envelope omits them entirely
  // when the funnel-counter table has zero rows for this scope) so buildFixture leaves `funnel`
  // as `{}` — populate both here so the populated-data branch (ciFunnelStepsMarkupV650), not
  // just the "no join/booking funnel data yet" empty branch, is actually exercised.
  fixture.funnel.join = { page_view: 10, started: 5, completed: 2 };
  fixture.funnel.booking = { page_view: 8, started: 4, completed: 1 };
  const html = runV650Block('funnelMarkupV650', {
    lastFunnelError: '', lastFunnelBundle: fixture,
  });
  assert.ok(typeof html === 'string' && html.length > 0);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

test('v723 contactabilityMarkupV650 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_contactability_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  const html = runV650Block('contactabilityMarkupV650', {
    lastContactabilityError: '', lastContactabilityBundle: fixture,
  });
  assert.ok(typeof html === 'string' && html.length > 0);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

/* ciCategoryCustomersRowsMarkupV650 is the category-mix drill-down (public.get_ci_category_
   customers_v1) — one layer more indirect than the three above: it reads
   `categoryCustomersCacheV650.get(nodeKey)`, a page-closure Map of {loading|error|data}, not a
   bundle variable directly. Exercised with a real Map holding the minimal contract fixture under
   `data`, same "supply the closure state, run the unmodified function" posture. */
const CATEGORY_CUSTOMERS_ROWS_BLOCK = extractBlock(
  'function ciCategoryCustomersRowsMarkupV650(nodeKey,expectedCustomerCount){',
  '/* nestly_v704 (check 66)',
);

test('v723 ciCategoryCustomersRowsMarkupV650 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_category_customers_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  fixture.suppressed = null; // exercise the customer-listing branch, not the suppressed-cohort one
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
  const scopeMoney = (c) => 'SGD ' + ((Number(c) || 0) / 100).toFixed(2);
  const walletDate = (v) => String(v ?? '');
  const categoryCustomersCacheV650 = new Map([['node1', { data: fixture }]]);
  const sandbox = { esc, scopeMoney, walletDate, categoryCustomersCacheV650, console };
  const context = vm.createContext(sandbox);
  context.__exports = {};
  vm.runInContext(`${CATEGORY_CUSTOMERS_ROWS_BLOCK}\n__exports.fn = ciCategoryCustomersRowsMarkupV650;`, context);
  const html = context.__exports.fn('node1', fixture.customers.length);
  assert.ok(typeof html === 'string' && html.length > 0);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

/* categoryMixMarkupV650 is not a pure function of a payload — it reads
   customerIntelligencePage's own closure variables (lastCategoryMixBundle/lastCategoryMixError/
   expandedCategoryNodesV650/categoryCustomersCacheV650). CATEGORY_MIX_REWRITES lists every
   substitution this test makes to turn it into a pure `(bundle) => html` function so it can be
   executed the same way as its siblings; a reviewer can diff this list against the real function
   to confirm nothing beyond parameter-wiring changed. */
const CATEGORY_MIX_REWRITES = [
  [/\blastCategoryMixError\b/g, 'null'],
  [/const\s+bundle\s*=\s*lastCategoryMixBundle;/, ''],  // bundle is already the parameter
  [/\blastCategoryMixBundle\b/g, 'bundle'],
  [/expandedCategoryNodesV650\.has\([^)]*\)/g, 'false'],
  [/ciCategoryCustomersRowsMarkupV650\([^)]*\)/g, "''"],
];

test('v723 categoryMixMarkupV650 renders the minimal contract fixture cleanly', () => {
  const contract = CONTRACTS['public.get_ci_category_mix_v1'];
  const fixture = buildFixture(contract.nested, contract.required);
  // The renderer's own withhold gate (CI_CATEGORY_MIX_READY_THRESHOLD_BPS_V650, real value 9000)
  // would otherwise fire on the generic leafValue(1) for classified_pct_bps and short-circuit
  // before touching categories/distribution — raise it here so the categories table branch,
  // not just the withheld-state branch, is actually exercised by this fixture.
  fixture.coverage.classified_pct_bps = 9500;

  const fnStart = appJs.indexOf('function categoryMixMarkupV650(){');
  const fnEnd = appJs.indexOf("  function ciCategoryMixWrapV650()", fnStart);
  assert.ok(fnStart > -1 && fnEnd > fnStart, 'categoryMixMarkupV650 must exist as a locatable function');
  let fnSource = appJs.slice(fnStart, fnEnd);
  for (const [pattern, replacement] of CATEGORY_MIX_REWRITES) fnSource = fnSource.replace(pattern, replacement);
  fnSource = fnSource.replace('function categoryMixMarkupV650(){', 'function categoryMixMarkupV650(bundle){');

  const distStart = appJs.indexOf('function ciCategoryDistributionRowMarkupV704(category){');
  const distEnd = appJs.indexOf('function categoryMixMarkupV650(){');
  const distSource = appJs.slice(distStart, distEnd);

  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
  const scopeMoney = (c) => 'SGD ' + ((Number(c) || 0) / 100).toFixed(2);
  const ciMeasuredSinceV650 = (since) => (since ? `<p>Measured since ${esc(since)}</p>` : '');
  const CI_CATEGORY_DISTRIBUTION_FLOOR_V704 = 5;
  // Real value at app/app.js:49450 — categoryMixMarkupV650 reads it directly (module scope, not
  // passed as a parameter), so the sandbox must supply the same constant.
  const CI_CATEGORY_MIX_READY_THRESHOLD_BPS_V650 = 9000;
  const sandbox = {
    esc, scopeMoney, ciMeasuredSinceV650, CI_CATEGORY_DISTRIBUTION_FLOOR_V704,
    CI_CATEGORY_MIX_READY_THRESHOLD_BPS_V650, console,
  };
  const context = vm.createContext(sandbox);
  context.__exports = {};
  vm.runInContext(`${distSource}\n${fnSource}\n__exports.fn = categoryMixMarkupV650;`, context);
  const html = context.__exports.fn(fixture);

  assert.ok(typeof html === 'string' && html.length > 0);
  assert.ok(!/\bundefined\b/.test(html), `renders "undefined": ${html.slice(0, 4000)}`);
  assert.ok(!/\bNaN\b/.test(html), `renders "NaN": ${html.slice(0, 4000)}`);
});

/* ---------------------------------------------------------- contract-declared-access checks */

test('v723 CONTRACT: funnelConversionPanelHtmlV679 reads only contract-declared paths', () => {
  const src = extractBlock('function funnelConversionPanelHtmlV679(payload){', '\n\n/* 2.');
  assertAccessesDeclared('public.get_ci_funnel_conversion_v1', src, {payload:'', p:''});
});

test('v723 CONTRACT: demographicsPanelHtmlV679 reads only contract-declared paths', () => {
  const src = extractBlock('function demographicsPanelHtmlV679(payload){', '\n\n/* 3.');
  assertAccessesDeclared('public.get_ci_demographics_v1', src, {payload:'', p:''});
});

test('v723 CONTRACT: behaviourPanelHtmlV679 reads only contract-declared paths', () => {
  const src = extractBlock('function behaviourPanelHtmlV679(payload){', '\n\n/* nestly_v650: Service mapping board');
  assertAccessesDeclared('public.get_ci_daypart_v1', src, {payload:'', p:''});
});

test('v723 CONTRACT: opportunitiesPanelHtmlV685 + ciOpportunityCardHtmlV685 read only contract-declared paths', () => {
  const src = extractBlock('function ciOpportunityConfidenceV685(confidence){', 'function ciMeasuredSinceInlineV679(');
  /* `impact`, `confidence`, `action` are destructured straight off `item` at the top of
     ciOpportunityCardHtmlV685 (`const action=item?.action||{},confidence=item?.confidence||{},
     impact=item?.impact||{};`) — extractAccesses' alias-assignment pass resolves these from the
     literal source, so no extra root vars are needed beyond `payload`/`item`. */
  /* `payload.error`/`payload.error.message` is opportunitiesPanelHtmlV685's own defensive guard
     against a client-constructed error wrapper (never a shape the real RPC emits — a failed RPC
     call never reaches this renderer at all; see ciFunnelConversionMarkupV679's sibling wiring
     one screen up, which intercepts lastOpportunitiesError before this pure function is called),
     so it is an allowed extra prefix rather than a contract gap. */
  assertAccessesDeclared('public.get_ci_opportunities_v1', src, {payload:'', item:'ranked.*'}, ['error']);
});

test('v723 CONTRACT: category mix renderer reads only contract-declared paths', () => {
  const fnStart = appJs.indexOf('function categoryMixMarkupV650(){');
  const fnEnd = appJs.indexOf('function ciCategoryMixWrapV650()', fnStart);
  const src = appJs.slice(fnStart, fnEnd).replace(/\blastCategoryMixBundle\b/g, 'bundle');
  assertAccessesDeclared('public.get_ci_category_mix_v1', src, {bundle:''});
});

test('v723 CONTRACT: acquisitionMarkupV650 reads only contract-declared paths', () => {
  const fnStart = appJs.indexOf('function acquisitionMarkupV650(){');
  const fnEnd = appJs.indexOf('function ciFunnelStepsMarkupV650(', fnStart);
  const src = appJs.slice(fnStart, fnEnd).replace(/\blastAcquisitionBundle\b/g, 'bundle');
  assertAccessesDeclared('public.get_ci_acquisition_v1', src, {bundle:''});
});

test('v723 CONTRACT: funnelMarkupV650 reads only contract-declared paths', () => {
  const fnStart = appJs.indexOf('function funnelMarkupV650(){');
  const fnEnd = appJs.indexOf('function ciContactabilityGroupMarkupV650(', fnStart);
  const src = appJs.slice(fnStart, fnEnd).replace(/\blastFunnelBundle\b/g, 'bundle');
  assertAccessesDeclared('public.get_ci_funnel_v1', src, {bundle:''});
});

test('v723 CONTRACT: contactabilityMarkupV650 reads only contract-declared paths', () => {
  const fnStart = appJs.indexOf('function contactabilityMarkupV650(){');
  const fnEnd = appJs.indexOf('const CI_CATEGORY_MIX_READY_THRESHOLD_BPS_V650=9000;', fnStart);
  const src = appJs.slice(fnStart, fnEnd).replace(/\blastContactabilityBundle\b/g, 'bundle');
  assertAccessesDeclared('public.get_ci_contactability_v1', src, {bundle:''});
});

test('v723 CONTRACT: ciCategoryCustomersRowsMarkupV650 reads only contract-declared paths', () => {
  const src = CATEGORY_CUSTOMERS_ROWS_BLOCK
    .replace('const customers=Array.isArray(cached.data?.customers)?cached.data.customers:[];',
      'const customers=data.customers;')
    .replace('const suppressed=cached.data?.suppressed||null;', 'const suppressed=data.suppressed||null;');
  assertAccessesDeclared('public.get_ci_category_customers_v1', src, {data:''});
});
